replicaCount: 1

image:
  repository: rjmateus/hw2025
  pullPolicy: IfNotPresent
  tag: "0.0.1" 

service:
  type: ClusterIP # Changed to internal service only
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: "traefik" # Recommended for K3s default ingress controller
  host: micro-62-k3s-node1.suse.local # The domain name you want to use
  path: /
  pathType: Prefix